let projectData;
export default projectData = [
        {
            id: crypto.randomUUID(),
            title: "VMST Communication Website",
            body: "This was the final project of my coding bootcamp. Together with my group, we found an organization that needed a website to facilitate communication with their members without reveling the members emails. This is the demo we presented to the class. The actual website is still being developed by me and another member of the group.",
            link: "https://github.com/ianmstevenson1/VMST-Communication-Website",
            deployedLink: "https://vmst-communication-website-352o.onrender.com",
            image: "/assets/projects/vmst-communication screenshot.png",
        },
        {
            id: crypto.randomUUID(),
            title: "Social-Network-API",
            body: "This was a project I did for a Social Network API, which was a part of my coding bootcamp. This 'challenge' was built around a noSQL database the accompanying APIs that I built. These APIs allow users to create accounts (in a limited capacity, no password), make 'thoughts' that are connected to their account, and add reactions to thoughts, as well as 'friend' other users. This was a backend-only challenge, so there's not much in the way of visual representation other than a screenshot of the code",
            link: "https://github.com/Spikey1289/Social-Network-API",
            deployedLink: null,
            image: "/assets/projects/social-networking-api screenshot.jpg",
        },
        {
            id: crypto.randomUUID(),
            title: "Tech-Blog",
            body: "This was a project for building a Tech-blog. As a part of my coding bootcamp, I made a full-stack application where users can create accounts, login, post blogposts, and comment on other users blogposts. The users are also able to edit and delete their own blogposts from their 'dashboard'. I used this challenge as a way to cement my knowledge of handlebars, designing back-end software, and about how data is communicated between the front and back end of the application. I also used this as a way to practice using Bulma for styling. The application is hosted on Heroku, provided by my bootcamp",
            link: "https://github.com/Spikey1289/Tech-Blog",
            deployedLink: "https://nameless-retreat-32005-714a98737ba8.herokuapp.com",
            image: "/assets/projects/tech-blog screenshot.png",
        },
        {
            id: crypto.randomUUID(),
            title: "Animals-Blog",
            body: "This was the second Group Project in my coding bootcamp. Our group made the decision to make a blog centered around users picking animals they liked. I do not own the repo in question, as I was not the one designated as the group leader in this project.",
            link: "https://github.com/ianmstevenson1/Animals-Blog",
            deployedLink: "https://taco-b1e076fa8a47.herokuapp.com",
            image: "/assets/projects/animals-blog screenshot.png",
        },
        // {
        //     id: crypto.randomUUID(),
        //     title: "Internet-Commerce-Back-End",
        //     body: "This is the backend of an Internet Commerce website. The challenge was a refactor challenge, so the main files were supplied to me by my coding bootcamp, and I supplied the models and the routes. The challenge was to get the software working so that you could make requests for data stored on the SQL database.",
        //     link: "https://github.com/Spikey1289/Internet-Commerce-Back-End",
        //     deployedLink: null,
        //     image: "/assets/projects/internet-commerce screenshot.jpg",
        // },
        {
            id: crypto.randomUUID(),
            title: "Employee_Tracker",
            body: "This is the backend for an Employee Tracker application. It uses SQL and MYSQL2/MYSQL2-Promise to make an application that can edit tables in a database.",
            link: "https://github.com/Spikey1289/Employee_Tracker",
            deployedLink: null,
            image: "/assets/projects/employee-tracker screenshot.jpg",
        },
        // {
        //     id: crypto.randomUUID(),
        //     title: "Note-Taker",
        //     body: "This is an application that is used to take notes on ones browser, and it wasn't functioning properly when it was supplied to me. Our challenge that week was to troubleshoot and fix the issues using express, fs, and path to generate/read from json files (the notes).",
        //     link: "https://github.com/Spikey1289/Note_Taker",
        //     deployedLink: "https://boiling-falls-75049-1f5f2e199c8d.herokuapp.com",
        //     image: "/assets/projects/note-taker screenshot.jpg",
        // },
        {
            id: crypto.randomUUID(),
            title: "Logo-Maker-SVG",
            body: "This application generates a custom logo based on user input. It's a relatively simple application that uses node JS and javascript. It was also one of the first applications where we had to give a walkthrough to potential users on how to use the app/install the app",
            link: "https://github.com/Spikey1289/Logo_Maker-SVG",
            deployedLink: null,
            image: "/assets/projects/logo-maker screenshot.jpg",
        },
        {
            id: crypto.randomUUID(),
            title: "Coding-Quiz",
            body: "This was a simple application that gave the user a quiz about coding in HTML, CSS, and JavaScript",
            link: "https://github.com/ianmstevenson1/Coding-Quiz",
            deployedLink: null,
            image: "/assets/projects/coding-quiz screenshot.png",
        },
        {
            id: crypto.randomUUID(),
            title: "drink_vtt_ICA",
            body: "This was the first Group Project in my coding bootcamp. Our group decided to make an application that provided instructions on how to make various kinds of drinks when a user selected them from a dropdown.",
            link: "https://github.com/ianmstevenson1/drink_vtt_ICA",
            deployedLink: null,
            image: "/assets/projects/drink-vtt-ICA screenshot.png",
        },
        {
            id: crypto.randomUUID(),
            title: "Ian's First Portfolio",
            body: "This was my first portfolio made during the coding bootcamp. It was a little more simple than this one, although it still serves as a progress marker to me for how far I've come.",
            link: "https://github.com/ianmstevenson1/Ians-Portfolio",
            deployedLink: null,
            image: "/assets/projects/ians-first-portfolio screenshot.png",
        },
        {
            id: crypto.randomUUID(),
            title: "Password-Generator",
            body: "This was a challenge revolving around making an application that would generate a random password based on user selected settings.",
            link: "https://github.com/ianmstevenson1/Password-Generator",
            deployedLink: null,
            image: "/assets/projects/password-generator screenshot.png",
        },
    ]